# Generated by Django 4.2 on 2024-10-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_featured'),
        ('userauths', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_videos',
            field=models.ManyToManyField(blank=True, related_name='saved_videos', to='core.video'),
        ),
    ]
