# Generated by Django 4.2 on 2024-10-12 04:19

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0003_channel_business_email_channel_business_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='business_location',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='make_business_email_public',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='make_business_location_public',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='website',
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=100)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
